[tool.poetry]
name = "minecraft_commands"
version = "0.1.0"
description = ""
authors = ["netuk <netuki1033@outlook.jp>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
